### ISSUE TITLE
Add stylua file

### ISSUE THREAD

**Issue by GCBallesteros** [SalOrak/whaler.nvim#10]
Having a stylua file and automatically formatting the codebase would make it easier to contribute PRs.

**Comment by SalOrak** [comment]
Thank you for your patience! Life got in the way of me doing side projects but I'm back!

Yeees! I was planning on adding a contribution guidelines too. 

But yeah, 100% here. 

And again, thank you for helping me shape whaler.

**Comment by SalOrak** [comment]
The commit [8d5300d](https://github.com/SalOrak/whaler.nvim/commit/8d5300d8935286ec2d3f80880fb34f8e7655f533) added the stylua file. 

It contains the basic preferences:
- 80 characters maximum per line.
- Indentation using spaces, at 4 spaces.
- Quote styling " over '.
- EOL in Unix (\n over \r\n)
