### ISSUE TITLE
[Feature Request] Allow relative paths

### ISSUE THREAD

**Issue by GCBallesteros** [SalOrak/whaler.nvim#15]
It would be very convenient to allow for relative paths. 

This is possible with builtin functions but another possible approach would be to use plenary (which the user will have anyways because it's a dependency for Telescope). Using plenary would then allow to simplify some code in the plugin by offloading[ path manipulation functionality to it](https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/path.lua).

I would be open to working on this if @SalOrak is interested on such a contribution.

**Comment by SalOrak** [comment]
Hey! Can you expand on the idea of relative paths in Whaler? Do you mean fuzzy finding directories inside a directory?

**Comment by GCBallesteros** [comment]
Just being able to use `~` or something like `~/../other_folder`. The readme says use absolute paths but does it already work?

Definitely not fuzzy finding or automagically finding the project root directory.

**Comment by SalOrak** [comment]
I've checked and the `~` only works on aliases. I remember that to expand a directory into multiple subdirectories I wanted the `~` to be expanded.

So yeeah, I think having relative paths is highly beneficial.

**Comment by SalOrak** [comment]
Done! Thank you! 

Because of the amount of work you've been doing I'll be adding a contributions section in the README. Thank you sooo much!
