### ISSUE TITLE
Configuring the theme doesn't seem to work

### ISSUE THREAD

**Issue by vivlim** [SalOrak/whaler.nvim#17]
I [tried to configure the theme](https://github.com/vivlim/vimfiles/blob/84264e59a6c73e79c744674a9aaac321968888a0/lua/plugins/navigation.lua#L28C10-L28C10) to make the window larger, since I have a lot of projects and want to be able to see more of them at once. But this had no effect:
```lua
    whaler = {
        theme = {
            results_title = true,
            layout_strategy = "center",
            layout_config = {
                height = 0.7,
                width = 0.7,
            },
        },
```

After trying a bunch of different things (setting `theme_opts` instead of `theme`, uncommenting [this line](https://github.com/SalOrak/whaler.nvim/blob/7ea55ec0551fcaa487d60ab363708f7a523786f5/lua/telescope/_extensions/whaler/main.lua#L193C1-L193C1)), I gave up and [forked the repo so I could override the default size](https://github.com/vivlim/whaler.nvim).

**Comment by SalOrak** [comment]
Hello! 

Yep that was a bug, thank you for reporting. You should be able to change the theme correctly using the following code in either the setup or in the keymap call
```lua
    --- more Whaler config here 
    theme = {
        previewer = false,
        layout_strategy = "center",
        layout_config = {
            height = 0.7,
            width = 0.7,
        },
    },
```

And by the way, the `results_title` variable is either `False` or a string with a name, otherwise telescope will raise an error. 

If it works close the issue.

**Comment by vivlim** [comment]
The window has the correct size *if* I specify the theme in a call to `telescope.extensions.whaler.whaler`, but the default size I specify in telescope's `setup` is still not being used. [This is what I tried](https://github.com/vivlim/vimfiles/blob/whaler-minimal/lua/plugins/navigation.lua), that branch removes everything from my config except for whaler, telescope, and lazy.

**Comment by SalOrak** [comment]
Hmmm thanks, I'll check it then.

**Comment by SalOrak** [comment]
Oh my god hahaha thank you! It was a bad conditional statement (== instead of ~=).

Could you try it out? It should be working now.

**Comment by vivlim** [comment]
That works, thanks!
