### ISSUE TITLE
Create compatability with telescope-file-explorer.

### ISSUE THREAD

**Issue by GotaLoveFiraCode** [SalOrak/whaler.nvim#7]
Would be awesome since it's part of the telescope family anyway. If this isn't achievable, it would be nice to just be able to add a custom command to execute after selection, e.g. so that you could just set `Telescope file_browser` and it would have the same effect. This might already be possible, not sure :|, maybe through setting a custom plugin for `file_explorer` (i.e. `file_explorer = "telescope"`) and then `file_explorer_config = { plugin_name = 'telescope', command = 'Telescope file_browser' }`. Either way, love the plugin :)!

**Comment by GotaLoveFiraCode** [comment]
Ok, I've been going through the code, and I see the issue. The telescope file browser only accepts paths through the `path=...` parameter. You can set `file_explorer_config = { command = "Telescope file_browser path=" }` but then whaler automatically add a space in between `path=` and the selection (i.e. `path= /home/username/Desktop`). This generates an error. The code that adds the space:
```lua
if auto_file_explorer then
    local cmd = vim.api.nvim_parse_cmd(file_explorer_config["command"] .. " " .. selection[1],{})
    vim.api.nvim_cmd(cmd, {})
end
```

A potential solution would be to just remove the space part (`file_explorer_config["command"] .. selection[1]`) and just tell the user to add a space if it's relevant for their command. Most of the time their not going to set this anyway, so they wont care.

**Comment by GotaLoveFiraCode** [comment]
After checking telescope docs I know the whole `path=...` to be true for all telescope pickers.

**Comment by SalOrak** [comment]
Wow, I didnt know about `Telescope file_browser`.

Yes, sure that would be defenitely good. Im planning on adding support to most of the file explorers so I really appreciate your contribution.

From the code perspective I noticed there is always an space between the command and the path. Im thinking about adding a `prefix_dir` to the configuration. This way its easier to change the codebase.

**Comment by GotaLoveFiraCode** [comment]
This would be absolutely incredible! I can't wait (no pressure though) :)!!!

**Comment by SalOrak** [comment]
Whaler now support a `prefix_dir` in the file explorer configuration. 
Also, `telescope-file-explorer` is now added to the out of the box support ;) 

Thanks for your contribution!
